[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ah_history"
version = "1.0.0"
description = "Chat history viewer plugin for Assistant Hub"
authors = [{name = "Assistant"}]
